version: "3"
services:
  # Database Container
  goblog-postgres:
    image: postgres:latest
    container_name: goblog_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - goblog

  # API Container
  app:
    container_name: goblog_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - goblog-postgres
    networks:
      - goblog

  # PG Admin Container
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - goblog-postgres
  #   ports:
  #     - "5050:80"    # pipe port 80 to 5050
  #   networks:
  #     - goblog
  #   restart: unless-stopped

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  goblog:
    driver: bridge
